version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: ronny-shop/app:latest
    networks:
    - appnet
    volumes:
    - .:/var/www/html
    ports:
    - ${DOCKER_APP_PORT}:80
    working_dir: /var/www/html
    environment:
      XDEBUG_HOST: ${DOCKER_XDEBUG_HOST}
      XDEBUG_IDEKEY: ${DOCKER_XDEBUG_IDEKEY}
      XDEBUG_PORT: ${DOCKER_XDEBUG_PORT}
  cache:
    image: redis:alpine
    networks:
    - appnet
    volumes:
    - cachedata:/data
    ports:
    - ${DOCKER_REDIS_PORT}:6379
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
    - ${DOCKER_DB_PORT}:3306
    networks:
    - appnet
    volumes:
    - dbdata:/var/lib/mysql
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: ronny-shop/node:latest
    networks:
    - appnet
    volumes:
    - .:/opt
    working_dir: /opt
    command: echo hi
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
